fix update script

diff --git a/module/system/xbin/r1update b/module/system/xbin/r1update
--- a/module/system/xbin/r1update
+++ b/module/system/xbin/r1update
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/system/bin/sh
 
 # Check if script is running as root
 if [ "$(id -u)" -ne 0 ]; then
@@ -21,20 +21,30 @@ check_file_existence() {
 # Check if all files exist
 check_file_existence "$r1_system_updater"
 check_file_existence "$r1_launcher"
+
 echo "Updating the launcher"
 # Replace system files
 if [ -f "/system/app/tech.rabbit.r1launcher.r2/base.apk" ]; then
     cp "$r1_launcher" "/system/app/tech.rabbit.r1launcher.r2/base.apk"
-    echo "Updated the launcher"
+    if [ $? -eq 0 ]; then
+        echo "Updated the launcher"
+    else
+        echo "Failed to update the launcher"
+    fi
 else
-    echo "Failed to update the launcher"
+    echo "Launcher file does not exist"
 fi
 
+echo "Updating the updater"
 if [ -f "/system/app/tech.rabbit.r1systemupdates/base.apk" ]; then
     cp "$r1_system_updater" "/system/app/tech.rabbit.r1systemupdates/base.apk"
-    echo "Updated the updater"
+    if [ $? -eq 0 ]; then
+        echo "Updated the updater"
+    else
+        echo "Failed to update the updater"
+    fi
 else
-    echo "Failed to update the updater"
+    echo "Updater file does not exist"
 fi
 
 echo "Rebooting"
